# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=1, help_text='Exchange rate against SEK, ie: if 1DKK = 1.30SEK, supplied value should be 1.3', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Currency'),
        ),
    ]
