# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20161119_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('brewery', models.ManyToManyField(related_name='beers', to='share.Brewery')),
                ('collabs', models.ManyToManyField(related_name='collab_beers', to='share.Brewery')),
            ],
        ),
        migrations.RemoveField(
            model_name='beer',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='Thumbnail',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='brewery',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='collabs',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='name',
        ),
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='ean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='share.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='base_beer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='share.AbstractBaseBeer'),
            preserve_default=False,
        ),
    ]
