# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20161119_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractbasebeer',
            name='collabs',
            field=models.ManyToManyField(blank=True, null=True, related_name='collab_beers', to='share.Brewery'),
        ),
    ]
