# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20161119_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beersize',
            name='volume',
            field=models.IntegerField(help_text='Volume in centiliters'),
        ),
    ]
