# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20161119_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
