# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20161119_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractbasebeer',
            name='brewery',
        ),
        migrations.AddField(
            model_name='abstractbasebeer',
            name='brewery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='share.Brewery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
