# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20161119_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, help_text='Describe your intentions with the list', null=True)),
                ('type', models.IntegerField(choices=[(0, 'Collab'), (1, 'Tasting')])),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BeerListBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ListBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(help_text='Use this to limit the number of times a beer can be claimed.')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use price in currency used by the site.', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareuser',
            name='get_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_messages', to='share.ShareUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='Users in list who has read the message.', null=True, to='share.ShareUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.BeerList'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='share.ShareUser'),
        ),
        migrations.AddField(
            model_name='listbeer',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Beer'),
        ),
        migrations.AddField(
            model_name='beerlistbeer',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Beer'),
        ),
        migrations.AddField(
            model_name='beerlistbeer',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.BeerList'),
        ),
        migrations.AddField(
            model_name='beerlistbeer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Only needed at collab-lists', null=True, on_delete=django.db.models.deletion.CASCADE, to='share.ShareUser'),
        ),
        migrations.AddField(
            model_name='beerlist',
            name='admins',
            field=models.ManyToManyField(help_text='Admins are allowed to invite new users, and add/remove beers from list', related_name='BeerListAdmin', to='share.ShareUser'),
        ),
        migrations.AddField(
            model_name='beerlist',
            name='beers',
            field=models.ManyToManyField(to='share.ListBeer'),
        ),
        migrations.AddField(
            model_name='beerlist',
            name='users',
            field=models.ManyToManyField(help_text='Users are only allowed to claim beers from the list', related_name='beerlistuser', to='share.ShareUser'),
        ),
    ]
