# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_auto_20161119_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerlist',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users are only allowed to claim beers from the list', null=True, related_name='beerlistuser', to='share.ShareUser'),
        ),
    ]
