# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20161120_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listbeer',
            name='qty',
            field=models.IntegerField(blank=True, help_text='Use this to limit the number of times a beer can be claimed.Not needed @ tasting-lists', null=True),
        ),
    ]
