# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0013_auto_20161120_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerlistbeer',
            name='list',
        ),
        migrations.AddField(
            model_name='beerlistbeer',
            name='qty',
            field=models.IntegerField(default=0, help_text='Number of this beer claimed by user.Can not be greater than ListBeer qty.Only needed at collab-lists'),
        ),
        migrations.AlterField(
            model_name='beerlistbeer',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.ListBeer'),
        ),
    ]
