# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_auto_20161120_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beerlistbeer',
            old_name='beer',
            new_name='listbeer',
        ),
        migrations.AlterField(
            model_name='beerlistbeer',
            name='qty',
            field=models.IntegerField(default=1, help_text='Number of this beer claimed by user.Can not be greater than ListBeer qty.Only needed at collab-lists'),
        ),
    ]
