# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_auto_20161120_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
